## Ex:2 Data Wrangling and Transformation 
### Objective

To perform data wrangling and transformation on a dataset using Python and Pandas by handling missing values, removing duplicates, correcting data types, filtering data, and transforming variables into a suitable format for data analysis and machine learning.



##  Dataset Description

The dataset contains information about **student academic performance, educational background, MBA specialization, and placement salary**.

###  Dataset Attributes

| Column | Description |
|:---|:---|
| `sl_no` | Serial number / student identifier |
| `gender` | Gender of the student |
| `hsc_p` | Higher Secondary / 12th percentage |
| `hsc_s` | Higher Secondary stream |
| `degree_p` | Undergraduate degree percentage |
| `degree_t` | Undergraduate degree type |
| `etest_p` | Employability / entrance test percentage |
| `specialisation` | MBA specialization |
| `mba_p` | MBA percentage |
| `salary` | Salary offered after placement |

---

## Experiment Question

 **Using the given student placement dataset, perform data wrangling and transformation by handling missing values, scaling numerical features, detecting and treating outliers, encoding categorical variables, and generating a final model-ready dataset.**

Data wrangling and transformation is the process of converting raw student placement data into a clean, consistent, and machine-learning-ready dataset. In this experiment, the given student placement dataset is first loaded into a Pandas DataFrame and explored by examining its rows, columns, data types, and descriptive statistics. Missing values are then identified and handled by removing records with missing `salary` values and replacing missing values in `hsc_p`, `degree_p`, and `etest_p` with their respective mean values. The numerical attributes such as `hsc_p`, `degree_p`, `etest_p`, and `salary` are transformed using feature-scaling techniques such as `StandardScaler` and `MinMaxScaler` to bring the variables into suitable numerical ranges. The dataset is then divided into input features (`X`) and the target variable (`Y`), where `salary` is considered the target. The preprocessed data is saved as `Pre.csv` for further processing. Next, possible outliers in the `salary` attribute are identified using a boxplot and statistically detected using the Z-score method, where values with an absolute Z-score greater than 3 are considered potential outliers. Outliers are also treated using the capping and flooring method by calculating the 5th and 95th percentiles and replacing values outside these limits with the corresponding boundary values. The salary distribution before and after outlier treatment is then compared using visualization. Since the dataset also contains categorical attributes such as `gender`, `hsc_s`, `degree_t`, and `specialisation`, these variables are converted into numerical representations using `LabelEncoder` and One-Hot Encoding. Finally, the completely transformed dataset is verified for missing values, data types, dimensions, and numerical representation, and the resulting model-ready dataset is saved as `Final.csv`. Thus, the experiment demonstrates the complete workflow of preparing real-world tabular data for data analysis and machine-learning applications.

## Step 1: Start by importing the necessary Python libraries for data preprocessing.

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from scipy.stats import zscore
from scipy import stats
from sklearn.preprocessing import LabelEncoder

## Step 2: Load the placement dataset into a Pandas Dataframe.

In [22]:
df=pd.read_csv("data.csv")
df.info()
df.shape
df.head()
df.tail()
df.sample(5)
df.describe()
df.loc[0]
df.iloc[0]
df[0:2]
df["degree_p"]

<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    str
 2   hsc_p           210 non-null    float64
 3   hsc_s           215 non-null    str
 4   degree_p        213 non-null    float64
 5   degree_t        215 non-null    str
 6   etest_p         211 non-null    float64
 7   specialisation  215 non-null    str
 8   mba_p           214 non-null    float64
 9   salary          148 non-null    float64
dtypes: float64(5), int64(1), str(4)
memory usage: 16.9 KB

0      58.00
1      77.48
2      64.00
3        NaN
4      73.30
       ...
210    77.60
211    72.00
212    73.00
213    58.00
214    53.00
Name: degree_p, Length: 215, dtype: float64

## Step 3:Take a quick look at the data to understand its structure and identify any missing values or anomalies.

#### The method isnull() checks each element in the DataFrame (or Series) to see if it is NaN (Not a Number) or None (missing value).
It returns a DataFrame (or Series) of the same shape as the input, with Boolean values:
#### True: The value is null (NaN or None).
#### False: The value is not null.

In [9]:
df.isnull().sum()

sl_no              0
gender             0
hsc_p              5
hsc_s              0
degree_p           2
degree_t           0
etest_p            4
specialisation     0
mba_p              1
salary            67
dtype: int64

## Step 4: Handle Missing Data
### Option 1: If the dataset is large and only a small percentage of data is missing, you can remove rows with missing values using dropna(subset,inplace)

In [12]:
df.dropna(subset=["salary"],inplace=True)
df.isnull().sum()

sl_no             0
gender            0
hsc_p             2
hsc_s             0
degree_p          1
degree_t          0
etest_p           2
specialisation    0
mba_p             0
salary            0
dtype: int64

['name', 'miles_per_gallon', 'cylinders', 'displacement', 'hp', 'weight_lbs', 'acceleration', 'year', 'origin', 'weight_kg', 'mpg_category', 'vehicle_age', 'origin_encoded']

### Option 2:If removing data isn't ideal, you can impute (df.[""].fillna(df[""].mean(),inplace)) missing values using methods like mean, median, or most frequent.

In [15]:
df["hsc_p"]=df["hsc_p"].fillna(df["hsc_p"].mean())
df["degree_p"]=df["degree_p"].fillna(df["degree_p"].mean())
df["etest_p"]=df["etest_p"].fillna(df["etest_p"].mean())
df.isnull().sum()

sl_no             0
gender            0
hsc_p             0
hsc_s             0
degree_p          0
degree_t          0
etest_p           0
specialisation    0
mba_p             0
salary            0
dtype: int64

## Step 5: Feature Scaling
Feature scaling is the process of converting numerical features to a similar scale so that one feature does not dominate another simply because it has larger numerical values.

<img src="https://i.postimg.cc/G21gMYnF/f.png" alt="Image Description" width="500">









## Option 1( StandardScaler): This method scales the data to have a mean of 0 and a standard deviation of 1.

In [23]:
c=["hsc_p","degree_p","etest_p","salary"]
s1=StandardScaler()
df[c]=s1.fit_transform(df[c])
df.head()

,sl_no,gender,hsc_p,hsc_s,degree_p,degree_t,etest_p,specialisation,mba_p,salary
0,1,M,2.251933,Commerce,-1.152628,Sci&Tech,-1.284412,Mkt&HR,58.80,-0.200292
1,2,M,1.087219,Science,1.513829,Sci&Tech,1.082489,Mkt&Fin,66.28,-0.951839
2,3,M,NaN,Arts,-0.331337,Comm&Mgmt,0.218382,Mkt&Fin,57.80,-0.415019
3,4,M,-1.333215,Science,NaN,Sci&Tech,-0.457875,Mkt&HR,59.43,NaN
4,5,M,0.652405,Commerce,0.941663,Comm&Mgmt,1.856428,Mkt&Fin,55.50,1.463849

#### Option 2:This method scales the data to a fixed range, usually between 0 and 1. 
###  MinMaxScaler()

In [24]:
s2=MinMaxScaler()
df[c]=s2.fit_transform(df[c])
df.head()

,sl_no,gender,hsc_p,hsc_s,degree_p,degree_t,etest_p,specialisation,mba_p,salary
0,1,M,0.889621,Commerce,0.195122,Sci&Tech,0.104167,Mkt&HR,58.80,0.094595
1,2,M,0.680890,Science,0.670244,Sci&Tech,0.760417,Mkt&Fin,66.28,0.000000
2,3,M,NaN,Arts,0.341463,Comm&Mgmt,0.520833,Mkt&Fin,57.80,0.067568
3,4,M,0.247117,Science,NaN,Sci&Tech,0.333333,Mkt&HR,59.43,NaN
4,5,M,0.602965,Commerce,0.568293,Comm&Mgmt,0.975000,Mkt&Fin,55.50,0.304054

## Step 6  Option 1: Identifying Outliers Using Z-Scores
The value of 3 in the context of Z-scores is often used as a threshold to identify outliers in a dataset. A Z-score represents how many standard deviations a data point is away from the mean of the dataset. Specifically:

A Z-score of 0 means the data point is exactly at the mean.
A Z-score of 1 means the data point is one standard deviation above the mean, and so on.
A Z-score of 3 corresponds to a data point being 3 standard deviations away from the mean. For a normal distribution, about 99.7% of the data points fall within 3 standard deviations of the mean (according to the 68-95-99.7 rule, which describes the spread of data in a normal distribution). Therefore, points with Z-scores greater than 3 or less than -3 are considered unusually far from the mean and are often flagged as outliers.

This threshold (Z > 3 or Z < -3) is commonly used in many statistical applications because it captures the extreme values that are rare in a normal distribution, which are typically considered to be outliers. However, the choice of threshold can vary depending on the specific application and the nature of the data.

[![Chat-GPT-Image-Aug-20-2026-08-06-05-PM.png](https://i.postimg.cc/2SFTtcXL/Chat-GPT-Image-Aug-20-2026-08-06-05-PM.png)](https://postimg.cc/4Yyz75GX)

In [32]:
columns_to_check = ["salary"]
z_score=stats.zscore(df[columns_to_check])
u=(z_score>3)
l=(z_score<-3)
indx = u | l
clean_df=df[~indx]
df.info()
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    str
 2   hsc_p           210 non-null    float64
 3   hsc_s           215 non-null    str
 4   degree_p        213 non-null    float64
 5   degree_t        215 non-null    str
 6   etest_p         211 non-null    float64
 7   specialisation  215 non-null    str
 8   mba_p           214 non-null    float64
 9   salary          148 non-null    float64
dtypes: float64(5), int64(1), str(4)
memory usage: 16.9 KB
<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    str
 2   hsc_p           210 non-null    float64
 3   hsc_s           215 non-null    str
 4   degree_p        213 non-null    float64
 5   degree_t        215 non-null    str
 6   etest_p         211 non-null    float64
 7   specialisation  215 non-null    str
 8   mba_p           214 non-null    float64
 9   salary          148 non-null    float64
dtypes: float64(5), int64(1), str(4)
memory usage: 16.9 KB

### Option 2:  Capping and Flooring Outliers
Capping and flooring is an outlier-treatment technique where extreme values are replaced with predefined boundary values instead of deleting the records.

In [33]:
l1=df["salary"].quantile(0.05)
u1=df["salary"].quantile(0.95)
df_capped=df.copy()
df_capped["salary"]=df_capped["salary"].clip(l1,u1)
df_capped.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    str
 2   hsc_p           210 non-null    float64
 3   hsc_s           215 non-null    str
 4   degree_p        213 non-null    float64
 5   degree_t        215 non-null    str
 6   etest_p         211 non-null    float64
 7   specialisation  215 non-null    str
 8   mba_p           214 non-null    float64
 9   salary          148 non-null    float64
dtypes: float64(5), int64(1), str(4)
memory usage: 16.9 KB

## Step 7: Convert categorical variables into numerical format using LabelEncoder ().
[![Picture1.png](https://i.postimg.cc/yNpNvnVd/Picture1.png)](https://postimg.cc/zLW5fCHZ)

In [35]:
L1=LabelEncoder()
df["gender"]=L1.fit_transform(df["gender"])
df["hsc_s"]=L1.fit_transform(df["hsc_s"])
df["degree_t"]=L1.fit_transform(df["degree_t"])
df["specialisation"]=L1.fit_transform(df["specialisation"])
df.head()

,sl_no,gender,hsc_p,hsc_s,degree_p,degree_t,etest_p,specialisation,mba_p,salary
0,1,1,0.889621,1,0.195122,2,0.104167,1,58.80,0.094595
1,2,1,0.680890,2,0.670244,2,0.760417,0,66.28,0.000000
2,3,1,NaN,0,0.341463,0,0.520833,0,57.80,0.067568
3,4,1,0.247117,2,NaN,2,0.333333,1,59.43,NaN
4,5,1,0.602965,1,0.568293,0,0.975000,0,55.50,0.304054

## Convert categorical variables into numerical format using one hot encoder

[![Picture2.png](https://i.postimg.cc/gcZ0Hv1J/Picture2.png)](https://postimg.cc/HjTHp7YD)

In [38]:
c=["gender"]
one_hot_encoded_data=pd.get_dummies(df,columns=c)
one_hot_encoded_data.to_csv('clean.csv',index=False)
one_hot_encoded_data.head()

,sl_no,hsc_p,hsc_s,degree_p,degree_t,etest_p,specialisation,mba_p,salary,gender_0,gender_1
0,1,0.889621,1,0.195122,2,0.104167,1,58.80,0.094595,False,True
1,2,0.680890,2,0.670244,2,0.760417,0,66.28,0.000000,False,True
2,3,NaN,0,0.341463,0,0.520833,0,57.80,0.067568,False,True
3,4,0.247117,2,NaN,2,0.333333,1,59.43,NaN,False,True
4,5,0.602965,1,0.568293,0,0.975000,0,55.50,0.304054,False,True

# Exercise: Data Cleaning and Transformation – Automobile Dataset

## Step 1: Load and Explore the Dataset

### 1. Load the Dataset
- Import Pandas and load the Automobile dataset.
- Display the first 10 rows.
- Display the shape of the dataset.

### 2. Explore the Dataset
- Display the column names.
- Display the data types.
- Generate descriptive statistics.
- Identify numerical and categorical columns.
- Display unique values in categorical columns.

## Step 2: Data Cleaning

### 3. Check Missing Values
- Check for missing values in each column.
- Display the number and percentage of missing values.

### 4. Handle Missing Values
- Replace missing numerical values using mean or median.
- Replace missing categorical values using mode.
- Verify that no missing values remain.

### 5. Remove Duplicate Records
- Check for duplicate rows.
- Display the number of duplicate records.
- Remove duplicate records.
- Verify the result.

### 6. Clean the `horsepower` Column
- Identify non-numeric values such as `?`.
- Replace `?` with `NaN`.
- Convert `horsepower` to numeric.
- Handle the resulting missing values.

## Step 3: Data Transformation

### 7. Transform the `origin` Column
- Display the unique values in `origin`.
- Convert the values into meaningful labels:
  - `1` → `usa`
  - `2` → `europe`
  - `3` → `japan`

### 8. Create `weight_kg`
- Create a new column `weight_kg`.
- Convert weight from pounds to kilograms.

  `weight_kg = weight × 0.453592`

### 9. Create `mpg_category`
Create a new column based on `mpg`:
- `< 20` → `Low`
- `20–29` → `Medium`
- `≥ 30` → `High`

### 10. Create `vehicle_age`
- Create a new column `vehicle_age`.
- Assume the current year is 2026.

  `vehicle_age = 2026 - model_year`

### 11. Rename Columns
Rename:
- `mpg` → `miles_per_gallon`
- `horsepower` → `hp`
- `weight` → `weight_lbs`
- `model_year` → `year`

### 12. Filter the Data
Display vehicles:
- With `mpg > 30`
- With `horsepower > 150`
- With `cylinders >= 6`
- Manufactured after 1980
- Originating from `usa`

## Step 4: Encoding Categorical Data

### 13. Label Encoding
- Apply `LabelEncoder` to the `origin` column.
- Create a new column `origin_encoded`.
- Display the original and encoded values.
- Display the category-to-label mapping.

### 14. One-Hot Encoding
- Apply One-Hot Encoding to the `origin` column.
- Compare Label Encoding and One-Hot Encoding.
- Which encoding method is more appropriate for `origin`? Explain why.

## Step 5: Outlier Detection

### 15. Identify Outliers Using Z-Scores
- Calculate the Z-score for the numerical features.
- Identify observations with `|Z-score| > 3` as outliers.
- Count the outliers in each numerical column.
- Display the rows containing outliers.
- Decide whether the outliers should be removed or retained.

## Step 6: Feature Scaling

### 16. Standardization Using StandardScaler
- Select the numerical features.
- Apply `StandardScaler`.
- Display the standardized values.
- Verify that the features have approximately mean `0` and standard deviation `1`.

## Step 7: Normalization

### 17. Normalization Using MinMaxScaler
- Apply `MinMaxScaler` to the numerical features.
- Transform the features to the range `[0, 1]`.
- Display the normalized values.
- Compare **Standardization** and **Normalization**.
- Explain when each scaling method is appropriate.

## Step 8: Create Features and Target

### 18. Create X and Y Variables
- Select the appropriate input features as **X (independent variables)**.
- Select `mpg` as **Y (target variable)**.
- Display the shape of `X` and `Y`.
- Save `X` and `Y` into `automobile_X_Y.csv`.
- Load the CSV file again and display the first 5 rows.

## Step 9: Save the Final Dataset

### 19. Save the Preprocessed Dataset
- Combine the processed features and target variable.
- Display the final dataset.
- Check for missing values.
- Save the final dataset as `automobile_preprocessed.csv`.

In [ ]:
import pandas as pd
import numpy as np
from scipy import stats
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler

df = pd.read_csv('Automobile.csv')

print(df.head(10))
print(df.shape)

In [ ]:
print(df.columns)
print(df.dtypes)
print(df.describe(include='all'))

num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = df.select_dtypes(include=['object']).columns.tolist()

print(num_cols)
print(cat_cols)

for col in cat_cols:
    print(col, df[col].unique())

In [ ]:
missing_count = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({'Missing Count': missing_count, 'Percentage': missing_pct})
print(missing_df)

In [ ]:
for col in num_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mean())

for col in cat_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mean()[0])

print(df.isnull().sum())

In [ ]:
duplicate_count = df.duplicated().sum()
print(duplicate_count)

df = df.drop_duplicates()
print(df.shape)

In [ ]:
if df['horsepower'].dtype == 'object':
    df['horsepower'] = df['horsepower'].replace('?', np.nan)
    df['horsepower'] = pd.to_numeric(df['horsepower'])
    df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

print(df['horsepower'].dtype)
print(df['horsepower'].isnull().sum())

In [ ]:
print(df['origin'].unique())

origin_mapping = {1: 'usa', 2: 'europe', 3: 'japan'}
if df['origin'].dtype in [np.int64, np.float64]:
    df['origin'] = df['origin'].map(origin_mapping)

print(df['origin'].unique())

In [ ]:
df['weight_kg'] = df['weight'] * 0.453592
print(df[['weight', 'weight_kg']].head())

In [ ]:
conditions = [
    (df['mpg'] < 20),
    (df['mpg'] >= 20) & (df['mpg'] < 30),
    (df['mpg'] >= 30)
]
choices = ['Low', 'Medium', 'High']

df['mpg_category'] = np.select(conditions, choices, default='Unknown')
print(df[['mpg', 'mpg_category']].head(10))

In [ ]:
if df['model_year'].max() < 100:
    df['vehicle_age'] = 2026 - (1900 + df['model_year'])
else:
    df['vehicle_age'] = 2026 - df['model_year']

print(df[['model_year', 'vehicle_age']].head())

In [ ]:
df = df.rename(columns={
    'mpg': 'miles_per_gallon',
    'horsepower': 'hp',
    'weight': 'weight_lbs',
    'model_year': 'year'
})

print(df.columns)

In [ ]:
filtered_mpg = df[df['miles_per_gallon'] > 30]
filtered_hp = df[df['hp'] > 150]
filtered_cylinders = df[df['cylinders'] >= 6]

year_threshold = 80 if df['year'].max() < 100 else 1980
filtered_year = df[df['year'] > year_threshold]
filtered_origin = df[df['origin'] == 'usa']

combined_filter = df[
    (df['miles_per_gallon'] > 30) &
    (df['hp'] > 150) &
    (df['cylinders'] >= 6) &
    (df['year'] > year_threshold) &
    (df['origin'] == 'usa')
]

print(combined_filter)

In [ ]:
le = LabelEncoder()
df['origin_encoded'] = le.fit_transform(df['origin'])

print(df[['origin', 'origin_encoded']].drop_duplicates())
mapping_dict = dict(zip(le.classes_, le.transform(le.classes_)))
print(mapping_dict)

In [ ]:
df_encoded = pd.get_dummies(df, columns=['origin'], prefix='origin', dtype=int)
print(df_encoded.head())

In [ ]:
numeric_features = ['miles_per_gallon', 'cylinders', 'displacement', 'hp', 'weight_lbs', 'acceleration']

z_scores = np.abs(stats.zscore(df[numeric_features]))
outlier_mask = (z_scores > 3).any(axis=1)

outliers_per_column = (z_scores > 3).sum(axis=0)
for col, count in zip(numeric_features, outliers_per_column):
    print(col, count)

outlier_rows = df[outlier_mask]
print(outlier_rows)

In [ ]:
scaler_standard = StandardScaler()
df_standardized = df.copy()

df_standardized[numeric_features] = scaler_standard.fit_transform(df[numeric_features])

print(df_standardized[numeric_features].head())
print(df_standardized[numeric_features].mean().round(4))
print(df_standardized[numeric_features].std().round(4))

In [ ]:
scaler_minmax = MinMaxScaler()
df_normalized = df.copy()

df_normalized[numeric_features] = scaler_minmax.fit_transform(df[numeric_features])

print(df_normalized[numeric_features].head())
print(df_normalized[numeric_features].min())
print(df_normalized[numeric_features].max())

In [ ]:
feature_columns = ['cylinders', 'displacement', 'hp', 'weight_lbs', 'acceleration', 'year', 'origin_encoded']

X = df[feature_columns]
Y = df['miles_per_gallon']

print(X.shape)
print(Y.shape)

xy_combined = pd.concat([X, Y], axis=1)
xy_combined.to_csv('automobile_X_Y.csv', index=False)

loaded_xy = pd.read_csv('automobile_X_Y.csv')
print(loaded_xy.head())

In [ ]:
final_df = df.copy()

print(final_df.head())
print(final_df.isnull().sum())

final_df.to_csv('automobile_preprocessed.csv', index=False)